{{- $app := .Values.apps.webapp }}
{{- if $app.enabled }}
{{- $ctx := dict "appName" "webapp" "appValues" $app "root" $ }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "radinage.fullname" $ctx }}
  labels:
    {{- include "radinage.labels" $ctx | nindent 4 }}
spec:
  {{- if not (dig "autoscaling" "enabled" $.Values.global.autoscaling.enabled $app) }}
  replicas: {{ default $.Values.global.replicaCount $app.replicaCount }}
  {{- end }}
  revisionHistoryLimit: {{ default $.Values.global.revisionHistoryLimit $app.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "radinage.selectorLabels" $ctx | nindent 6 }}
  template:
    metadata:
      {{- include "radinage.podMetadata" $ctx | nindent 6 }}
    spec:
      {{- include "radinage.podSpec" $ctx | nindent 6 }}
      containers:
        - name: webapp
          {{- include "radinage.containerSpec" $ctx | nindent 10 }}
          env:
            - name: API_HOST
              value: {{ include "radinage.apiHost" $ | quote }}
            {{- with $app.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- include "radinage.volumeMounts" $ctx | nindent 10 }}
      {{- include "radinage.volumes" $ctx | nindent 6 }}
      {{- include "radinage.scheduling" $ctx | nindent 6 }}
{{- end }}
