{{- $app := .Values.apps.webapp }}
{{- if $app.enabled }}
{{- if (dig "serviceAccount" "create" $.Values.global.serviceAccount.create $app) }}
{{- $ctx := dict "appName" "webapp" "appValues" $app "root" $ }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "radinage.serviceAccountName" $ctx }}
  labels:
    {{- include "radinage.labels" $ctx | nindent 4 }}
  {{- include "radinage.serviceAccountAnnotations" $ctx | nindent 2 }}
automountServiceAccountToken: {{ default $.Values.global.serviceAccount.automountServiceAccountToken (dig "serviceAccount" "automountServiceAccountToken" false $app) }}
{{- end }}
{{- end }}
